services:
  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - AGENT_BACKEND=${AGENT_BACKEND:-langgraph}
      - PYTHONPATH=/app
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app
      - backend_venv:/app/.venv
    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 8001
    restart: unless-stopped

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - VITE_API_BASE=http://localhost:8001
      - BACKEND_URL=http://backend:8001
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 5173
    restart: unless-stopped

volumes:
  backend_venv:
